excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://kenandjackie.github.io
title: Ken Caron and Jackie Bkizzard's Wedding
tagline: We're getting hitched
description: July 8, 2017
paginate: 5
