excerpt_separator: ""
highlighter: true
markdown: kramdown
url: http://kenandjackie.github.io
title: Ken Caron and Jackie Blizzard's Wedding
tagline: We're getting hitched
description: We're getting married!
